---
title: "Final Project Draft"
author: "Chase Garcia"
date: "Due 4/21/2022"
output: html_document
---


```{r}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
load("all_guns.RData")


save(Auto_Rifles, Bows, Breech_Grenade_Launchers, Fusion_Rifles, Hand_Cannons, Heavy_Grenade_Launchers, Linear_Fusion_Rifles, Machine_Guns, Pulse_Rifles, Rocket_Launchers, Scout_Rifles, Shotguns, Sidearms, Sniper_Rifles, Submachine_Guns, Swords, file = "all_guns.RData")

```

```{r}
gun_data <- bind_rows(Auto_Rifles, Bows, Breech_Grenade_Launchers, Fusion_Rifles, Hand_Cannons, Heavy_Grenade_Launchers, Linear_Fusion_Rifles, Machine_Guns, Pulse_Rifles, Rocket_Launchers, Scout_Rifles, Shotguns, Sidearms, Sniper_Rifles, Submachine_Guns, Swords)

view(gun_data)

```

```{r}

Primary <- gun_data %>% filter(Ammo =="Primary")

Special <- gun_data %>% filter(Ammo == "Special")

Heavy <- gun_data %>% filter(Ammo == "Heavy")



```





```{r}

##Auto Rifles are fully automatic weapons that thrive in close-medium range encounters. Their 2 top values would be RoF and Body Damage.

##There are 9 Auto rifles with more than 390 ROF and more than 20 body damage
top_autos <- Auto_Rifles %>% filter(Body_dmg > 20 & RoF > 350)

##Scouts are semi automatic which specialize in range and precision. Their top two specialties will rely on their Crit damage and Optimal amount of shots for a kill

##
top_scouts 

Scout_Rifles %>% filter(Crit_dmg > 50 & Opt_Shots < 3.1)

Scout_Rifles %>% filter(RoF > 150 & Body_dmg > 30)

#Hand cannons 

##Their top attributes you want to look for are Range, Stability and 
top_hand_cannons <- Hand_Cannons %>% filter(Range > 55 & Stability > 55)

##Pulse Rifles

##Pulse rifles are a ranged weapon that shoot in bursts of 3.4 or 5 and specialize in medium ranged combat

top_pulse <- Pulse_Rifles %>% filter(Range > 55 & Stability > 55 & RoF > 350)

#Sub Machine Guns

#Sub machine guns are fully automatic weapons with very limited range and their defining features are it RoF, Handling and Stability

top_subs <- Submachine_Guns %>% filter(RoF > 700 & Handling > 55 & Stability > 55)

#Bows

#Bows are Long ranges weapons that typically take 2-3 shot to take someone out. What you want to look for in a bow are a quick draw time, high impact, and/or good accuracy.

top_bows <- Bows %>% filter(Draw_Time < 700 & Impact > 70 & Accuracy > 50)

#Fusion Rifles

#Fusion Rifles are energy base weapons which you start with limited ammo and can only be shot twice before needing to pick up from a dead player. The features you look for in a good fusion rifle are Low charge time, Handling and high impact.

top_fusions <- Fusion_Rifles %>% filter(`Charge_Time(ms)`<.8 & Handling > 40 & Impact > 60)

#Shotguns

#Shotguns are very close quarter combat weapons that will usualy 1 shot anyone within their effective range. There for we are going to want to look for one with good range, impact, and stability. 

top_shotguns <- Shotguns %>% filter(Impact > 65 & Handling > 60)

#Side Arms

#side arms are not the most effective in PVP but can still be viable in certain situations. Side arms thrive in close to medium combat and tend to have good handling, good recoil control and decent RoF.

top_sidearms <- Sidearms %>% filter(Handling > 50 & Recoil_Direction > 95)

#Breaching Grenade Launchers
#Blast Radius, Velocity and Reload speed or handling

top_bgl <- Breech_Grenade_Launchers %>% filter(Blast_Radius > 54, Velocity > 75 & Reload_Speed > 70)

#Sniper Rifles

#Sniper rifles require special ammo which means you only start with 2 shots. However they do 1 have 1 shot capabilities like other weapons that use special ammo. Sniper excel in long range combat so the specs you will want to look out for are its handling, low zoom magnification and Aim_assist(for controller players)

top_snipers <- Sniper_Rifles %>% filter(Handling > 40 & Lowest_Zoom < 55 & Aim_Assist > 60)

#Linear Fusion Rifles

#Linear Fusion rifles require special ammo and have one shot capabilities as well but they require time to charge up and unlike normal fusion rifles these only shoot one time per charge. Since these weapons excel in medium to long range you want to look out for stats like low charge time and good handling

top_linear <- Linear_Fusion_Rifles %>% filter(`Charge_Time(ms)`> 500 & Handling > 35)

#Rocket Launchers
#Blast Radius and Velocity

top_rockets <- Rocket_Launchers %>% filter(Blast_Radius > 74 & Velocity > 50)

#Heavy Grenade Launchers
#Blast Radius and Velocity

top_hgl <- Heavy_Grenade_Launchers %>% filter(Blast_Radius > 20 & Velocity > 40)

#Machine Guns
#Either high body damage and good range or high RoF and good handling

top_mg <- Machine_Guns %>% filter(Body_dmg > 29 & Range > 65)

#Swords 
#Speed and Impact

top_swords <- Swords %>% filter(Speed > 45 & Impact > 59)

```


```{r}

top_weapons <- bind_rows(top_autos, top_bgl, top_bows, top_fusions, top_hand_cannons, top_hgl, top_linear, top_mg, top_pulse, top_rockets, top_scouts, top_shotguns, top_sidearms, top_snipers, top_subs, top_swords)

view(top_weapons)


```

```{r}

ggplot(data = top_weapons) + geom_bar(mapping = aes(x = Energy, fill = Ammo)) + ggtitle("Energy distribution using top weapons")

ggplot(data = gun_data) + geom_bar(mapping = aes(x = Energy)) + ggtitle("Energy distribution using all weapons")


tw <- top_weapons %>% ggplot(aes(Range, Stability, color = Type, text = Weapon)) + geom_point() + facet_wrap(~Ammo)

library(plotly)
ggplotly(tw)

ggplotly(Auto_Rifles %>% ggplot(aes(Body_dmg, Stability, text = Weapon)) + geom_point())



```






```{r}
##Graph Ideas
gun_data %>% ggplot(aes(Crit_dmg, Body_dmg)) + geom_point()

gun_data %>% ggplot(aes(`Optimal_TtK(s)`)) + geom_histogram()

ggplot(data = gun_data) + 
  geom_bar(mapping = aes(x = Archetype, fill = Energy)) + ggtitle("Amount of each Archetype")

```













